### ISSUE TITLE
jrebel error

### ISSUE THREAD

**Issue by 2377h** [igoriakovlev/JumpToLine#11]
When starting a project with jrebel debug mode, the cursor cannot be dragged.

env: win 11
ide:   2022.3.2   -   IU-223.8617.56

**Comment by igoriakovlev** [comment]
Oh my gosh :/

**Comment by guazixiong** [comment]
Me too，After jrebel starts debugging, after dragging the cursor, the code starts and ends from the cursor position, but does not jump to the debugging node I expect.

**Comment by anqli8341** [comment]
idea 插件启动服务异常环境信息如下：
1 机器 macbookpro m3
2 jdk 版本 17
3 idea 2024.1.4

rror: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at java.base/com.zeroturnaround.jrebelbase.reorder.a.a(SourceFile:21)
	at java.base/com.zeroturnaround.jrebelbase.reorder.b.a(SourceFile:138)
	at java.base/com.zeroturnaround.jrebelbase.reorder.b.markJRebelInitalized(SourceFile:128)
	at com.zeroturnaround.javarebel.hpt.a(SourceFile:343)
	at com.zeroturnaround.javarebel.hpt.deferredInitHook(SourceFile:184)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:40001)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl._jrLoadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.base/com.zeroturnaround.jrebelbase.reorder.a.a(SourceFile:18)
	... 5 more
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 54
Exception Details:
  Location:
    jtracker/IIiiiIIiiII.add(Ljava/lang/Object;)V @54: aload_2
  Reason:
    Type 'java/lang/Object' (current frame, locals[0]) is not assignable to 'jtracker/IIiiiIIiiII' (stack map, locals[0])
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'java/lang/Object', 'java/lang/Object', 'java/lang/Object' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @54
    flags: { }
    locals: { 'jtracker/IIiiiIIiiII', top, 'java/lang/Object' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0000000: 1100 0057 2ab8 00dd 594d c22a 2b4b 4c2b
    0000010: b700 2a2a 59b6 007a b800 f1ba 0084 0000
    0000020: b900 8803 0012 0db8 00d5 c000 0d2a 01b6
    0000030: 008c 572c c3b1 2cc3 b800 e8c0 0059 bf  
  Exception Handler Table:
    bci [11, 54] => handler: 54
  Stackmap Table:
    full_frame(@54,{Object[#2],Top,Object[#4]},{Object[#89]})

	at jtracker.IiiIIIIIIIi.<clinit>(ufa)
	at jtracker.IiiiIIiIIII.<init>(kja:455)
	at jtracker.IiiiIIiIIII.<init>(kja:177)
	at jtracker.iiiiiIiIIiI.<clinit>(lda:150)
	at jtracker.iIIIIIIiIIi.IIIiIiIiiiii(hca:6)
	at jtracker.iIIIIIIiIIi.premain(hca:123)
	... 11 more
